# Generated by Django 4.1 on 2022-10-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workArea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_area',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
